### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by Abu-Hijleh** [data301-2020-winter2/course-project-group_1043#3]
Must fix:
- [ ] Nicholas: need to fix importing the functions from the scripts folder , make sure to use relative addressing not absolute addressing. 
- [ ] Melissa: missing EDA in folder 
- [ ] Confusion between task 4 and task 5. Task 4 required you to each work on an individual EDA in your folders, and then work on an in depth analysis with research questions in the general analysis folder. I see an EDA in Nicholas work, and some elements of task 5 in Jordan's work. You need to work on fleshing task 5 out by conducting more analysis.

**Comment by jribbink** [comment]
Melissa dropped the course
